apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: your-dockerhub-username/backend-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: mongodb://admin:123$@mongo:27017/social-media?authSource=admin
