apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: socialmedia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: zunair77/social-media-frontend:latest
          ports:
            - containerPort: 3000
