name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure Docker to use Minikube's Docker daemon
      - name: Configure Docker to use Minikube
        run: |
          echo "Setting Docker env to Minikube..."
          minikube docker-env | Invoke-Expression

      # Step 3: Set kubectl context to Minikube
      - name: Set kubectl context to Minikube
        run: |
          kubectl config use-context minikube

      # Step 4: List directory contents for debugging
      - name: List directory contents (Debugging)
        run: |
          dir

      # Step 5: Build and start containers using Docker Compose
      - name: Build and start containers using Docker Compose
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml up -d

      # Step 6: Login to Docker Hub using the Access Token
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 7: Push images to Docker Hub (optional)
      - name: Push images to Docker Hub (optional)
        run: |
          docker-compose -f docker-compose.yml push

      # Step 8: Apply Kubernetes Manifests
      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
