name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Docker to use Minikube
        run: |
          echo "Setting Docker env to Minikube..."
          minikube docker-env | Invoke-Expression

      - name: Set kubectl context to Minikube
        run: |
          kubectl config use-context minikube

      - name: List directory contents (Debugging)
        run: |
          dir

      - name: Build and start containers using Docker Compose
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml up -d

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push images to Docker Hub (optional)
        run: |
          docker-compose -f docker-compose.yml push

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
